name: Push Request for Teams

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  check-duplicates:
    runs-on: ubuntu-latest
    permissions:
    pull-requests: read
    contents: read
    defaults:
      run:
        working-directory: ./duplicates
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v5
      - name: Make the script files executable
        run: chmod +x duplicates.sh
      - name: Run the scripts
        run: |
          ./duplicates.sh